#pragma kernel InitGrid

#include "./MpmStruct.hlsl"
#include "./Constant.hlsl"
#include "./Grid.hlsl"
#include "./SVD.hlsl"

#define THREAD_1D 256

RWStructuredBuffer<MpmCell> _GridBuffer;

[numthreads(THREAD_1D,1,1)]
void InitGrid(uint3 DTid : SV_DispatchThreadID)
{
	uint idx = DTid.x;
	MpmCell cell = _GridBuffer[idx];
	cell.mass = 0;
	cell.mass_x_velocity = 0;
	cell.force = 0;
	cell.velocity = 0;
	_GridBuffer[idx] = cell;
}
